AM62X/AM62PX: Android: Change repo init url to use https://
When using shallow clones on repo init using:

$ repo init -u https://git.ti.com/git/android/manifest.git \
       -b android14-release -m releases/RLS_09_02.xml --depth=1
$ repo sync device/ti/am62x

We see the following errors from git.ti.com:

error: Server does not allow request for unadvertised object 70a3161f12e2685c0e9eecbdf237ac1d56e5cb09
error: Cannot fetch android/device-ti-am62x from git://git.ti.com/android/device-ti-am62x

This can't be reproduced using https:// and older manifests must remain
useable.

Switch all repo init command to use https:// instead of git://

Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>